version: '3.9'

services:
  postgresDB:
    image: postgres
    container_name: database_disaster

    env_file:
      - ./.env

    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/data/postgres

  # app: 
  #   build: .
  #   container_name: app_disaster
    
  #   env_file:
  #   - ./.env
    
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - postgresDB
  #   depends_on:
  #     - postgresDB

volumes:
  pgdata:
    driver: local
